/**
 * Lista Oficial de Tipos Suportados na collection errosintegracoes (MongoDB Read-Only)
 */
export const TIPOS_ERROS_INTEGRACOES = [
  "Anúncio",
  "Atributo",
  "Atributo Valor",
  "Categoria",
  "Cliente",
  "Comissão",
  "Contato",
  "Custo",
  "Departamento",
  "Documento",
  "Empresa",
  "Estoque",
  "Etiqueta",
  "Frete",
  "Imagens Atributo Valor FTP",
  "Imagens Produtos",
  "Imagens Produtos FTP",
  "Lançamento",
  "Local",
  "Marca",
  "Orçamento",
  "Pedido",
  "Pedido Cancelado",
  "Pedido Concluído",
  "Pedido Enviado",
  "Pedido Etiqueta",
  "Pedido Faturado",
  "Pedido Faturado Canal",
  "Pedido Liberado",
  "Pedido Status Tms",
  "Personalizado",
  "Preço",
  "Produto",
  "Produto Empresa",
  "Repasse",
  "Tabela de Preço",
  "Transferência",
  "Transportadora",
  "Variação",
  "Vendedor",
] as const;

export type TipoErroIntegracao = (typeof TIPOS_ERROS_INTEGRACOES)[number];
